### ISSUE TITLE
Please use sqlalchemy

### ISSUE THREAD

**Issue by mimi89999** [hugo213/staszic-zapisy#2]
Please use sqlalchemy and database models.

**Comment by olus2000** [comment]
Wypierdalaj

**Comment by janekjan** [comment]
The size of this project is inadequate for using such tools. We might consider it at a later date, though.

**Comment by olus2000** [comment]
Sorry for my former lack of proffesional attitude, Michel has shown his value for our project, and any form of help is appreciated.
