### ISSUE TITLE
plz use SQL JOIN

### ISSUE THREAD

**Issue by wdyzewski** [hugo213/staszic-zapisy#3]
https://github.com/hugo213/staszic-zapisy/blob/7f7db1de2a46d04ae253c436bb1293bcc7694fa1/main/obsluga_maili.py#L40

**Comment by olus2000** [comment]
Nie rozumiem w jaki sposób użycie joina poprawiłoby ten kod.

**Comment by wdyzewski** [comment]
Ok, rzut oka na linie 39-42 wyglądał, że użyta konstrukcja programistyczna jest zupełnie nonsesnsowna. W połączeniu z template wysyłającym mail jednak ma nieco więcej sensu (choć nadal nie wydaje mi się optymalne - jeśli `db.execute()` ładuje od razu wyniki zapytania do pamięci, to może lepiej po stronie pythona dzielić całość tabeli `wizyty` po nauczycielach?).

**Comment by olus2000** [comment]
Jeżeli dobże zrozumiałem byłby to overkill kyóry nie przyspieszyłby działania systemu. Dzielenie tabeli musielibyśmy wykonywać kodem napisanym przez nas, więc wolę zaufać niskopoziomowej bazie że zrobi to lepiej.
